- name: Build & Deploy Docker container
  hosts: dockerservers
  gather_facts: false
  remote_user: root
  tasks:
    - name: copy the files to remote server
      become: true
      copy:
        src: /var/lib/jenkins/workspace/ansible-jenkins-pipeline
        dest: ~/project/
        remote_src: true
    - name: Building Docker Image
      docker_image:
        name: carvilla:latest
        build:
          path:~/project
        state: present
    - name: Stopping Container if already running
      docker_container:
       name: carvilla-container
       image: carvilla:latest
       state: stopped
    - name: Removing Container after running
      docker_container:
       name: carvilla-container
       image: carvilla:latest
       state: absent
    - name: Creating the Container
      docker_container:
       name: carvilla-container
       image: carvilla:latest
       ports:
        - "80:80"
       state: started